//! TOML emission for vocab groups: deterministic, grouped, reviewable.

use std::fmt::Write;

use crate::merge::MergedTerm;

/// Slugify a term into a stable entry id.
pub fn slugify(term: &str) -> String {
    let mut out = String::new();
    let mut prev_dash = true; // suppress leading dash
    for c in term.chars() {
        if c.is_ascii_alphanumeric() {
            out.push(c.to_ascii_lowercase());
            prev_dash = false;
        } else if !prev_dash {
            out.push('-');
            prev_dash = true;
        }
    }
    while out.ends_with('-') {
        out.pop();
    }
    out
}

/// TOML basic string with proper escapes (handles apostrophes cleanly).
fn toml_lit(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '\r' => out.push_str("\\r"),
            c if (c as u32) < 0x20 => {
                use std::fmt::Write as _;
                let _ = write!(out, "\\u{:04X}", c as u32);
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// Render one vocab group file. Terms are chunked alphabetically so no
/// single file is unwieldy; each renders as one `[[entries]]` block.
#[allow(clippy::too_many_arguments)]
pub fn vocab_group(
    chunk_index: usize,
    id_base: &str,
    category: &str,
    advice_group: Option<&str>,
    terms: &[MergedTerm],
) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "# Generated by crates/convert — do not edit by hand.");
    let _ = writeln!(out, "id-base = {}", toml_lit(id_base));
    let _ = writeln!(out, "kind = \"vocab\"");
    let _ = writeln!(out, "tier = 2");
    let _ = writeln!(out, "category = {}", toml_lit(category));
    let _ = writeln!(out, "enabled = true");
    let _ = writeln!(out);
    // One [[entries]] block per chunk: terms share group-level advice.
    let _ = writeln!(out, "[[entries]]");
    let _ = writeln!(out, "slug = \"chunk-{}\"", chunk_index + 1);
    if let Some(advice) = advice_group {
        let _ = writeln!(out, "advice = {}", toml_lit(advice));
    }

    let _ = writeln!(out, "terms = [");
    for t in terms {
        let _ = writeln!(out, "  {},", toml_lit(&t.term));
    }
    let _ = writeln!(out, "]");
    let _ = writeln!(out);
    out
}
