//! TOML emission for vocab groups: deterministic, grouped, reviewable.

use std::fmt::Write;

use crate::merge::MergedTerm;
use std::path::Path;

/// Slugify a term into a stable entry id.
pub fn slugify(term: &str) -> String {
    let mut out = String::new();
    let mut prev_dash = true; // suppress leading dash
    for c in term.chars() {
        if c.is_ascii_alphanumeric() {
            out.push(c.to_ascii_lowercase());
            prev_dash = false;
        } else if !prev_dash {
            out.push('-');
            prev_dash = true;
        }
    }
    while out.ends_with('-') {
        out.pop();
    }
    out
}

/// Phase-4 seed advice (spec t7c7): exactly one entry per representative
/// shape, consumed by golden snapshot tests before bulk rollout.
pub fn seed_advice(kind_seed: &str) -> Option<&'static str> {
    Some(match kind_seed {
        // vocab-with-replacement: fixable rewrite instruction
        "term=leverage" => {
            "Replace \"{match}\" with its plain verb (\"use\") — nominalized business-speak is a top frequency signal in Kobak 2025"
        }
        // vocab-without: report-only framing guidance
        "term=a testament to" => {
            "\"{match}\" performs admiration instead of analysis; state what it actually demonstrates"
        }
        _ => return None,
    })
}

/// Override used by pattern emission for named-capture seeds.
pub fn seed_pattern_advice(name: &str) -> Option<&'static str> {
    Some(match name {
        "negative-parallelism" => {
            "Drop the negation scaffold and state it positively: roughly \"{payload}\""
        }
        _ => return None,
    })
}

/// TOML basic string with proper escapes (handles apostrophes cleanly).
pub fn toml_lit(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '\r' => out.push_str("\\r"),
            c if (c as u32) < 0x20 => {
                use std::fmt::Write as _;
                let _ = write!(out, "\\u{:04X}", c as u32);
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// Render one vocab group file. Terms are chunked alphabetically so no
/// single file is unwieldy; each renders as one `[[entries]]` block.
#[allow(clippy::too_many_arguments)]
/// Advice strings are hand-authored after generation (phase 7) but the
/// converter regenerates whole files. Harvest `slug -> advice` from the
/// CURRENT generated file so regeneration preserves authored content;
/// empty map when the file is absent (first run).
pub fn harvest_advice(pack: &Path, fname: &str) -> std::collections::BTreeMap<String, String> {
    let mut map = std::collections::BTreeMap::new();
    let Ok(text) = std::fs::read_to_string(pack.join(fname)) else {
        return map;
    };
    let mut current_slug: Option<String> = None;
    for line in text.lines() {
        let line = line.trim();
        if let Some(rest) = line.strip_prefix("slug = ") {
            current_slug = Some(rest.trim_matches('\'').trim_matches('"').to_string());
        } else if let Some(rest) = line.strip_prefix("advice = ") {
            if let Some(slug) = current_slug.take() {
                // Keep the raw TOML value (with its original quoting) so
                // re-emission is byte-identical.
                map.insert(slug, rest.trim().to_string());
            }
        }
    }
    map
}

pub fn vocab_group(
    chunk_index: usize,
    id_base: &str,
    category: &str,
    advice_group: Option<&str>,
    terms: &[MergedTerm],
    saved: &std::collections::BTreeMap<String, String>,
) -> String {
    use std::borrow::Cow;
    let mut out = String::new();
    let _ = writeln!(out, "# Generated by crates/convert — do not edit by hand.");
    let _ = writeln!(out, "id-base = {}", toml_lit(id_base));
    let _ = writeln!(out, "kind = \"vocab\"");
    let _ = writeln!(out, "tier = 2");
    let _ = writeln!(out, "category = {}", toml_lit(category));
    let _ = writeln!(out, "enabled = true");
    let _ = writeln!(out);
    // Split report-only terms: seeded ones become their own entries.
    let report_only: Vec<&MergedTerm> = terms.iter().filter(|t| t.replacement.is_none()).collect();

    // Seed report-only terms: carve the seeded term into its own entry so
    // golden tests exercise the vocab-without-replacement shape.
    let seeded: Vec<&MergedTerm> = terms
        .iter()
        .filter(|t| t.replacement.is_none() && seed_advice(&format!("term={}", t.term)).is_some())
        .collect();
    let report_only: Vec<&MergedTerm> = report_only
        .into_iter()
        .filter(|t| seed_advice(&format!("term={}", t.term)).is_none())
        .collect();
    for t in seeded {
        let slug = slugify(&t.term);
        let _ = writeln!(out, "[[entries]]");
        let _ = writeln!(out, "slug = {}", toml_lit(&slug));
        match saved.get(&slug).filter(|a| !a.is_empty()) {
            // Raw preserved value: emit exactly as found.
            Some(raw) => {
                let _ = writeln!(out, "advice = {raw}");
            }
            None => {
                let _ = writeln!(
                    out,
                    "advice = {}",
                    toml_lit(seed_advice(&format!("term={}", t.term)).expect("seeded"))
                );
            }
        }
        let _ = writeln!(out, "terms = [{}]", toml_lit(&t.term));
        let _ = writeln!(out);
    }
    if report_only.is_empty() {
        return out;
    }
    let _ = writeln!(out, "[[entries]]");
    let _ = writeln!(out, "slug = \"chunk-{}\"", chunk_index + 1);
    if let Some(advice) = advice_group {
        let _ = writeln!(out, "advice = {}", toml_lit(advice));
    }
    let _ = writeln!(out, "terms = [");
    for t in &report_only {
        let _ = writeln!(out, "  {},", toml_lit(&t.term));
    }
    let _ = writeln!(out, "]");

    // Fixable entries: one `[[entries]]` per replacement-bearing term so
    // each carries its own machine-fixable `replacement`. Slugs carry a
    // disambiguating ordinal because normalized terms can collide
    // ("additionally" vs "additionally,").
    let mut fix_ord = 0usize;
    for t in terms.iter().filter(|t| t.replacement.is_some()) {
        fix_ord += 1;
        let _ = writeln!(out, "[[entries]]");
        let _ = writeln!(
            out,
            "slug = {}",
            toml_lit(&format!("{}-fix-{fix_ord}", slugify(&t.term)))
        );
        let saved_key = format!("{}-fix-{fix_ord}", slugify(&t.term));
        match saved.get(&saved_key).filter(|a| !a.is_empty()) {
            Some(raw) => {
                let _ = writeln!(out, "advice = {raw}");
            }
            None => {
                let advice: Option<Cow<'_, str>> = seed_advice(&format!("term={}", t.term))
                    .map(Cow::from)
                    .or(advice_group.map(Cow::from));
                if let Some(advice) = advice {
                    let _ = writeln!(out, "advice = {}", toml_lit(&advice));
                }
            }
        }
        let _ = writeln!(out, "terms = [{}]", toml_lit(&t.term));
        let _ = writeln!(
            out,
            "replacement = {}",
            toml_lit(t.replacement.as_deref().unwrap_or_default())
        );
        let _ = writeln!(out);
    }

    out
}
