//! NOTICE.toml generation: one per pack, embedding frozen SHAs.

use std::fmt::Write;

/// One upstream source with its snapshot provenance.
pub struct Upstream {
    pub repo: &'static str,
    pub commit: &'static str,
    pub license: &'static str,
}

/// The five sources, recorded at clone time (phase-4 task tsq8).
pub const UPSTREAMS: [Upstream; 5] = [
    Upstream {
        repo: "https://github.com/walidboulanouar/anti-ai-slop",
        commit: "37d1175523f1880aff8f3c4230905177e75dd183",
        license: "MIT",
    },
    Upstream {
        repo: "https://github.com/theserverlessdev/wsc",
        commit: "202391de9e0020e8f23faab9ae10ae6c2601253c",
        license: "MIT",
    },
    Upstream {
        repo: "https://github.com/MikkoParkkola/anti-ai-tell",
        commit: "c7ab8a388228587359c626e929052ce291435fd2",
        license: "MIT",
    },
    Upstream {
        repo: "https://github.com/hardikpandya/stop-slop",
        commit: "8da1f030185bdfe8471220585162991eaeb970e9",
        license: "MIT",
    },
    Upstream {
        repo: "https://github.com/jere-mie/unslop",
        commit: "afba7c77feb77b4885168462643a1cb01249c17a",
        license: "MIT",
    },
];

/// Render the NOTICE body listing every upstream this pack drew from.
pub fn render(repo_filter: &[&str]) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "# Generated by crates/convert — do not edit by hand.");
    for up in &UPSTREAMS {
        if !repo_filter.is_empty() && !repo_filter.iter().any(|r| up.repo.contains(r)) {
            continue;
        }
        let _ = write!(
            out,
            "\n[[origin]]\nrepo = \"{}\"\ncommit = \"{}\"\nlicense = \"{}\"\n",
            up.repo, up.commit, up.license
        );
    }
    out
}
